package com.mafqud.android.auth.login.models
import androidx.annotation.Keep
import com.squareup.moshi.Json


@Keep
data class LoginResponse(
    @field:Json(name = "access")
    val access: String = "", // eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjUzMjQzODQ2LCJpYXQiOjE2NTMyNDM1NDYsImp0aSI6ImVmMDQ4MjliMzFlOTRjZDBiZmQ2MmZlMTg5ODRkY2JmIiwidXNlcl9pZCI6MiwibmFtZSI6Ik9zYW1hIFlhc3NlciBTYWJlciIsInBob25lIjoiMTAwNTQ2OTk3MiIsIm5hdGlvbmFsX2lkIjpudWxsLCJmaXJlYmFzZV90b2tlbiI6InNhZHRva2VuIiwiZ292IjoiXHUwNjI3XHUwNjQ0XHUwNjQyXHUwNjI3XHUwNjQ3XHUwNjMxXHUwNjI5IiwiY2l0eSI6Ilx1MDYyN1x1MDY0NFx1MDYyOFx1MDYzM1x1MDYyN1x1MDYyYVx1MDY0YVx1MDY0NiJ9.PC-QFeDXOupDg6wCMHDcoEAubMc2o5YTT5xPpos9hm0
    @field:Json(name = "refresh")
    val refresh: String = "" // eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY1MzMyOTk0NiwiaWF0IjoxNjUzMjQzNTQ2LCJqdGkiOiJiYjA5YWUyZDcwZDc0MTJhYmUwZGJjZmZjNTg2NzExZSIsInVzZXJfaWQiOjIsIm5hbWUiOiJPc2FtYSBZYXNzZXIgU2FiZXIiLCJwaG9uZSI6IjEwMDU0Njk5NzIiLCJuYXRpb25hbF9pZCI6bnVsbCwiZmlyZWJhc2VfdG9rZW4iOiJzYWR0b2tlbiIsImdvdiI6Ilx1MDYyN1x1MDY0NFx1MDY0Mlx1MDYyN1x1MDY0N1x1MDYzMVx1MDYyOSIsImNpdHkiOiJcdTA2MjdcdTA2NDRcdTA2MjhcdTA2MzNcdTA2MjdcdTA2MmFcdTA2NGFcdTA2NDYifQ.PiCGFhJs6ttSuOuVWbzVsm1XXqLaNAs_nlwGWUKjBMc
)