## 1 (workflow name)
name: Build and Deploy to play store(Internal test)

## 2 (conditions) -> Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - v*.*.*-*

## some vars
env:
  APP_NAME: MafQud
  RELEASE_VERSION: ${ steps.vars.outputs.tag }
  INTERNAL_APP_LINK: https://play.google.com/apps/internaltest/4698997697459283178
  PUBLIC_APP_LINK: https://play.google.com/store/apps/details?id=com.mafqud.android

jobs:
  build_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      #      - name: Build Project
      #        run: ./gradlew build

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.mafqud.android
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          #whatsNewDirectory: whatsnew/
          track: internal
          status: completed


  discord_notification:
    needs: [ build_Deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      # for printing app version name in workflow
      - name: Check version output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: 0x00FF00
          avatar_url: ${{ secrets.DISCORD_AVATAR }}
          username: |
            ${{ env.APP_NAME }} application
          title: |
            :star2:  New version of ${{ env.APP_NAME }} is ready!
          description: |
            :clipboard: Version `${{ env.RELEASE_VERSION }}`
            :outbox_tray: Click [here](${{ env.INTERNAL_APP_LINK }}) to install!

  telegram_notification:
    needs: [ build_Deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New version of ${{ steps.vars.outputs.tag }} is ready!
            Version: ${{ steps.vars.outputs.tag }}
            Click to install!
            ${{ env.INTERNAL_APP_LINK }}